#!/usr/bin/env bash
set -euo pipefail

PKG_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Locations (honour XDG if set)
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"
PREFIX_DIR="$XDG_DATA_HOME/daily-note"
SCRIPTS_DIR="$PREFIX_DIR/scripts"
SAMPLE_VAULT_DIR="$PREFIX_DIR/sample-vault"


echo "Installing daily-note to: $PREFIX_DIR"

mkdir -p "$PREFIX_DIR"
mkdir -p "$XDG_BIN_HOME"

echo "Copying package files..."
rsync -a --exclude '.git' --exclude 'tests' --exclude 'dist' --exclude '.venv' "$PKG_ROOT/" "$PREFIX_DIR/"

chmod -R u+rwX,go+rX "$PREFIX_DIR"

# Ensure main script is executable
if [ -f "$SCRIPTS_DIR/main.sh" ]; then
  chmod +x "$SCRIPTS_DIR/main.sh"
fi

# Create `obs` shim in user local bin
OBS_SHIM="$XDG_BIN_HOME/obs"
echo "Creating shim: $OBS_SHIM -> $SCRIPTS_DIR/main.sh"
cat > "$OBS_SHIM" <<EOF
#!/usr/bin/env bash
exec "$SCRIPTS_DIR/main.sh" "\$@"
EOF
chmod +x "$OBS_SHIM"

# Prepare .env in scripts dir so lib.sh will find it when installed
ENV_FILE="$SCRIPTS_DIR/.env"
echo "# Generated by install.sh" > "$ENV_FILE"

## Non-interactive / scripted options
INSTALL_SAMPLE=0
YES=0
OVERRIDE_VAULT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --yes)
      YES=1; INSTALL_SAMPLE=1; shift ;;
    --sample-vault)
      INSTALL_SAMPLE=1; shift ;;
    --vault-path)
      OVERRIDE_VAULT="$2"; shift 2 ;;
    --help)
      echo "Usage: $0 [--yes|--sample-vault|--vault-path <path>]"; exit 0 ;;
    *) echo "Unknown option: $1"; exit 2 ;;
  esac
done

if [ -n "$OVERRIDE_VAULT" ]; then
  VAULT_PATH="$OVERRIDE_VAULT"
  VAULT_PATH="${VAULT_PATH/#\~/$HOME}"
  if [ -d "$VAULT_PATH" ]; then
    echo "VAULT_DIR=$VAULT_PATH" >> "$ENV_FILE"
    echo "Configured VAULT_DIR -> $VAULT_PATH"
  else
    echo "Provided vault path does not exist: $VAULT_PATH" >&2
    exit 2
  fi
elif [ "$INSTALL_SAMPLE" -eq 1 ]; then
  mkdir -p "$SAMPLE_VAULT_DIR"
  if [ -d "$PKG_ROOT/notes/samples" ]; then
    rsync -a "$PKG_ROOT/notes/samples/" "$SAMPLE_VAULT_DIR/"
  fi
  echo "VAULT_DIR=$SAMPLE_VAULT_DIR" >> "$ENV_FILE"
  echo "Installed sample vault at: $SAMPLE_VAULT_DIR"
else
  if [ "$YES" -eq 1 ]; then
    # default to sample vault if --yes provided
    mkdir -p "$SAMPLE_VAULT_DIR"
    if [ -d "$PKG_ROOT/notes/samples" ]; then
      rsync -a "$PKG_ROOT/notes/samples/" "$SAMPLE_VAULT_DIR/"
    fi
    echo "VAULT_DIR=$SAMPLE_VAULT_DIR" >> "$ENV_FILE"
    echo "Installed sample vault at: $SAMPLE_VAULT_DIR"
  else
    # interactive fallback
    read -rp "Install sample vault to $SAMPLE_VAULT_DIR? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      mkdir -p "$SAMPLE_VAULT_DIR"
      if [ -d "$PKG_ROOT/notes/samples" ]; then
        rsync -a "$PKG_ROOT/notes/samples/" "$SAMPLE_VAULT_DIR/"
      fi
      echo "VAULT_DIR=$SAMPLE_VAULT_DIR" >> "$ENV_FILE"
      echo "Installed sample vault at: $SAMPLE_VAULT_DIR"
    else
      # ask if user has existing vault
      read -rp "Do you have an existing vault to use? (y/N) " -n 1 -r
      echo
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        read -rp "Enter path to your vault directory: " VAULT_PATH
        VAULT_PATH="${VAULT_PATH/#\~/$HOME}"
        if [ -d "$VAULT_PATH" ]; then
          echo "VAULT_DIR=$VAULT_PATH" >> "$ENV_FILE"
          echo "Configured VAULT_DIR -> $VAULT_PATH"
        else
          echo "Path does not exist: $VAULT_PATH" >&2
          echo "Leaving VAULT_DIR unset. You can edit $ENV_FILE later." >&2
        fi
      else
        echo "No vault configured. You can edit $ENV_FILE later to set VAULT_DIR." >&2
      fi
    fi
  fi
fi

# If VAULT_DIR is set, check git remotes and offer to configure gitea remote
VAULT_DIR_SET=$(grep -E '^VAULT_DIR=' "$ENV_FILE" || true)
if [ -n "$VAULT_DIR_SET" ]; then
  VAULT_DIR_VAL=$(sed -n 's/^VAULT_DIR=//p' "$ENV_FILE" | tr -d '"')
  if [ -d "$VAULT_DIR_VAL/.git" ] || git -C "$VAULT_DIR_VAL" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "Detected git repository in vault: $VAULT_DIR_VAL"
    # List remotes
    git -C "$VAULT_DIR_VAL" remote -v
    if git -C "$VAULT_DIR_VAL" remote | grep -qx gitea; then
      echo "Remote 'gitea' already present." 
      GIT_URL=$(git -C "$VAULT_DIR_VAL" remote get-url gitea 2>/dev/null || true)
      if [ -n "$GIT_URL" ]; then
        echo "GIT_REMOTE_NAME=gitea" >> "$ENV_FILE"
        echo "GIT_REMOTE_URL=$GIT_URL" >> "$ENV_FILE"
      fi
    else
      # If other remotes exist, offer to map one to 'gitea'
      existing_remotes=$(git -C "$VAULT_DIR_VAL" remote)
      if [ -n "$existing_remotes" ]; then
        echo "Available remotes: $existing_remotes"
        read -rp "Would you like to add one of these remotes as 'gitea'? (y/N) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
          echo "Choose a remote to alias as 'gitea':"
          select r in $existing_remotes; do
            if [ -n "$r" ]; then
              url=$(git -C "$VAULT_DIR_VAL" remote get-url "$r")
              git -C "$VAULT_DIR_VAL" remote add gitea "$url"
              echo "Added remote gitea -> $url"
              echo "GIT_REMOTE_NAME=gitea" >> "$ENV_FILE"
              echo "GIT_REMOTE_URL=$url" >> "$ENV_FILE"
              break
            fi
          done
        fi
      else
        # no remotes: ask to add one
        read -rp "No remotes found. Add a remote URL now to create 'gitea'? (y/N) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
          read -rp "Enter remote git URL (ssh or https): " remote_url
          git -C "$VAULT_DIR_VAL" remote add gitea "$remote_url"
          echo "Added remote gitea -> $remote_url"
          echo "GIT_REMOTE_NAME=gitea" >> "$ENV_FILE"
          echo "GIT_REMOTE_URL=$remote_url" >> "$ENV_FILE"
        fi
      fi
    fi
  fi
fi

cat <<EOF
Installation complete.

Installed to: $PREFIX_DIR
Command shim: $OBS_SHIM
Env file: $ENV_FILE

You can edit $ENV_FILE to tweak settings (e.g. VAULT_DIR).
Run 'obs' to start the main tool.
EOF

exit 0
