name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up bash environment
        run: |
          sudo apt-get update
          sudo apt-get install -y coreutils curl

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/*.sh || true
          chmod +x ./tests/*.sh || true

      - id: ensure_host
        name: Ensure CI server hostname resolves (host mapping)
        if: always()
        env:
          GITEA_HOST_IP: ${{ secrets.HOST_IP }}
        run: |
          echo "HOST_IP ${GITEA_HOST_IP:-}"
          if [ -z "${GITEA_HOST_IP:-}" ]; then
            echo "GITEA_HOST_IP not set; skipping hosts mapping"
            exit 0
          fi

          echo "Adding hosts entry: ${GITEA_HOST_IP} gitea"
          # append mapping to /etc/hosts (requires sudo in runner)
          sudo bash -c "echo '${GITEA_HOST_IP} gitea' >> /etc/hosts"

      - name: Run tests
        run: |
          ./tests/run_tests.sh

      - name: Upload test logs
        if: steps.ensure_host.outputs.ensure_host_status == '-1'
        run: |
          echo "Uploading test logs (if any)"
          # create a tarball of tests/logs if it exists
          if [ -d tests/logs ]; then
            tar czf test-logs.tar.gz -C tests logs || true
            ls -l test-logs.tar.gz || true
          else
            echo "No tests/logs directory present"
          fi
        continue-on-error: true
