name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name : Set up bash environment
        run: |
          sudo apt-get update
          sudo apt-get install -y coreutils

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/*.sh || true
          chmod +x ./tests/*.sh || true

      - name: Verify repository .env
        run: |
          if [ -f .env ]; then
            echo ".env present in repository root"
          else
            echo ".env not found in repository root. CI requires a .env for runtime configuration; failing." >&2
            exit 1
          fi

      - name: Set VERSION for build
        run: |
          # Prefer env-provided VERSION, else pick latest RELEASE_NOTES/v.*.md, else git tag
          if [ -n "${VERSION:-}" ]; then
            echo "Using provided VERSION=$VERSION"
            echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          elif ls RELEASE_NOTES/v.*.md >/dev/null 2>&1; then
            v=$(ls RELEASE_NOTES/v.*.md | sed -E 's#.*/(v[0-9]+\.[0-9]+\.[0-9]+)\.md#\1#' | sort -V | tail -n1)
            echo "Detected VERSION from RELEASE_NOTES: $v"
            echo "VERSION=$v" >> "$GITHUB_ENV"
          else
            t=$(git describe --tags --abbrev=0 2>/dev/null || echo "v.0.0.0")
            echo "Detected VERSION from git: $t"
            echo "VERSION=$t" >> "$GITHUB_ENV"
          fi

      - name: Run tests
        env:
          # ensure scripts use an isolated VAULT_DIR inside runner workspace
          VAULT_DIR: "${{ github.workspace }}/.test-vault"
        run: |
          mkdir -p "${VAULT_DIR}"
          tests/run_tests.sh

      - name: Ensure logs directory exists
        if: always()
        run: |
          # create logs dir under the runner workspace to avoid empty-path issues
          mkdir -p "$PWD/tests/logs"
          ls -la "$PWD/tests/logs" || true

      - name: Ensure 'gitea' hostname resolves (CI host mapping)
        if: always()
        env:
          GITEA_HOST: "gitea"
          GITEA_PORT: ${{ secrets.GITEA_PORT }}
          HOST_IP: ${{ secrets.HOST_IP }}
        run: |
          set -euo pipefail
          echo "Checking connectivity to ${GITEA_HOST}${GITEA_PORT:+:$GITEA_PORT}"
          try_curl() {
            local host="$1" port="$2"
            if [ -n "$port" ]; then
              curl -fsS --connect-timeout 5 "http://$host:$port" >/dev/null 2>&1 && return 0 || true
              curl -fsS --connect-timeout 5 "https://$host:$port" >/dev/null 2>&1 && return 0 || true
            else
              curl -fsS --connect-timeout 5 "http://$host" >/dev/null 2>&1 && return 0 || true
              curl -fsS --connect-timeout 5 "https://$host" >/dev/null 2>&1 && return 0 || true
            fi
            return 1
          }

          if try_curl "$GITEA_HOST" "$GITEA_PORT"; then
            echo "Successfully reached $GITEA_HOST${GITEA_PORT:+:$GITEA_PORT}"
            exit 0
          fi

          echo "Could not reach $GITEA_HOST${GITEA_PORT:+:$GITEA_PORT} via network. Checking secrets for HOST_IP..."
          if [ -n "${HOST_IP:-}" ]; then
            echo "HOST_IP secret present: will append to /etc/hosts"
            echo "Adding hosts entry: ${HOST_IP} ${GITEA_HOST}"
            sudo bash -c "echo '${HOST_IP} ${GITEA_HOST}' >> /etc/hosts"
            grep -F "${HOST_IP} ${GITEA_HOST}" /etc/hosts || true
            # try curl again after mapping
            if try_curl "$GITEA_HOST" "$GITEA_PORT"; then
              echo "Successfully reached $GITEA_HOST after hosts mapping"
              exit 0
            else
              echo "Still cannot reach $GITEA_HOST after adding hosts entry" >&2
              exit 1
            fi
          else
            echo "No HOST_IP secret provided and hostname is unreachable; failing." >&2
            exit 1
          fi

      - name: Upload test logs
        if: always()
        # Use v3 of upload-artifact for GHES compatibility
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: tests/logs/**
